const { Sequelize } = require('sequelize');
const fs = require('fs');
if (fs.existsSync('config.env')) require('dotenv').config({ path: './config.env' });


function convertToBool(text, fault = 'true') {
    return text === fault ? true : false;
}
module.exports = {
ALIVE_MSG: process.env.ALIVE_MSG === undefined ? 'default' : process.env.ALIVE_MSG,
LANG: process.env.LANG === undefined ? '' : process.env.LANG,
ALIVE_LOGO: process.env.ALIVE_LOGO === undefined ? 'https://i0.wp.com/trenovision.com/wp-content/uploads/2020/03/official-WHO-bot.jpg' : process.env.ALIVE_LOGO,
FOOTER: process.env.FOOTER === undefined ? 'ᴀꜱᴛʀᴏ-ᴍᴅ ᴍᴏᴠɪᴇ ᴅʟ ʙᴏᴛ' : process.env.FOOTER,
CAPTION: process.env.CAPTION === undefined ? 'Generated By Astro Bot' : process.env.CAPTION,
ONLY_GROUP: process.env.ONLY_GROUP === undefined ? 'true' : process.env.ONLY_GROUP,
INBOX_BL_MSG: process.env.INBOX_BL_MSG === undefined ? 'https://chat.whatsapp.com/JNeNwzBHY2w1nF7H9LRKhS\n\n*Join Group*' : process.env.INBOX_BL_MSG,
HOST: process.env.HOST === undefined ? '' : process.env.HOST,
SESSION_ID: process.env.SESSION_ID === undefined ? 'ASTRO=sioXWIqS#Q744cn-P14dj3tRQAJfOzPUXlY1JxgyOMeRvFvr5J6U' : process.env.SESSION_ID
};
